version: '3.7'

services:
  webserver:
    container_name: webserverTRAIRCRM
    image: nginx
    restart: always
    volumes:
      - "./docker/app.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - php
      - postgres
    networks:
      - app-network

  php:
    container_name: phpTRAIRCRM
    build: docker
    restart: always
    environment:
      PHP_IDE_CONFIG: "serverName=server-backend"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
    volumes:
      - ".:/var/www/html"
    networks:
      - app-network

  postgres:
    container_name: postgresTRAIRCRM
    image: postgres:12
    restart: always
    ports:
      - "54325:5432"
    environment:
      - POSTGRES_USER=superadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=trair-crm
      - TZ=GMT
    volumes:
      - "./postgresql-data:/var/lib/postgresql/data"
    networks:
      - app-network
  #mysql:
  #  container_name: mysql
  #  image: mysql:5.6
  #  command: --default-authentication-plugin=mysql_native_password
  #  restart: always
  #  ports:
  #    - "33306:3306"
  #  environment:
  #    - MYSQL_DATABASE=trair-crm
  #    - MYSQL_ROOT_PASSWORD=root
  #    - MYSQL_HOST=localhost
  #  networks:
  #    - app-network
volumes:
  postgresql-data:

networks:
  app-network:
    driver: bridge
